version: '3'
services:
  frontend:
    image: bd240897/true-tech-hack-frontend
    environment:
      - VUE_APP_API_URL="http://91.185.84.82:3004"
      - VUE_APP_VIDEO_URL="http://91.185.84.82:8000/video/"
    # Запускаем vue + mock-server
    command: npm run both
    ports:
      - "8080:8080"
      - "3004:3004"
  backend:
    image: bd240897/true-tech-hack-backend
    # Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"