version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    # Запускаем vue + mock-server
    env_file:
      - frontend.env
    command: npm run both
    ports:
      - "8080:8080"
      - "3004:3004"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"