version: '3'
services:
  ml:
    # Берем Dockerfile из каталога app
    image: bd240897/true-tech-hack
    restart: always
    # Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"